[project]
name = "agentinfer"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["datasets", "fastapi", "httpx", "numpy", "prometheus-client", "PyYAML", "pydantic", "tqdm", "uvicorn"]

[tool.setuptools.packages.find]
include = ["agentinfer*"]

[project.scripts]
vllm = "agentinfer.agentcache.entrypoints.cli.main:main"

[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = [
    "E501", # line too long, handled by formatter
]

[tool.ruff.lint.isort]
known-first-party = ["agentinfer"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
